import type { Metadata } from 'next'
import { MarketingHero } from '@/components/marketing/MarketingHero'
import { MarketingPageShell } from '@/components/marketing/MarketingPageShell'
import { MarketingSection, MarketingSectionHeader } from '@/components/marketing/marketing-primitives'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: 'What TurboPanel collects, why, and how to control it.',
}

const LAST_UPDATED = '2026-09-12'

function H3({ children }: Readonly<{ children: React.ReactNode }>) {
  return <h3 className="mt-8 text-lg font-semibold text-[var(--tp-text)]">{children}</h3>
}

function P({ children }: Readonly<{ children: React.ReactNode }>) {
  return <p className="mt-3 text-sm leading-relaxed text-[var(--tp-text-muted)]">{children}</p>
}

export default function PrivacyPage() {
  return (
    <MarketingPageShell active="privacy">
      <MarketingHero
        eyebrow="Legal"
        title="Privacy Policy"
        description={`Last updated ${LAST_UPDATED}. This covers the hosted TurboPanel service at turbopanel.app. A self-hosted instance sends TurboPanel nothing — the data described below lives entirely on your own servers and your own database.`}
      />

      <MarketingSection className="pt-0">
        <div className="mx-auto max-w-3xl rounded-2xl border border-[var(--tp-amber-line,theme(colors.amber.400/40))] bg-[var(--tp-surface-muted)]/60 px-5 py-4 text-sm text-[var(--tp-text-muted)]">
          <strong className="text-[var(--tp-text)]">Draft, not legal advice.</strong> Written to match
          what the hosted service actually collects today; needs attorney review — particularly the
          international-transfer and regional-rights sections — before it governs real signups.
        </div>

        <MarketingSectionHeader title="1. Self-hosted vs. hosted" />
        <P>
          If you run TurboPanel yourself, this policy doesn&apos;t apply to that instance — there is no
          connection back to TurboPanel, no telemetry phoned home, and no data collected by us. Your
          organization, your servers, your database. Everything below is specific to the hosted service
          at <code>turbopanel.app</code>.
        </P>

        <H3>2. Information we collect</H3>
        <P>
          <strong className="text-[var(--tp-text)]">Account information</strong> — your email address,
          name if provided, and organization details, whether you sign up directly or via a connected
          OAuth provider (GitHub or GitLab, for repository access).
        </P>
        <P>
          <strong className="text-[var(--tp-text)]">Billing information</strong> — for paid tiers,
          Stripe collects and stores your payment details directly; we receive and retain only what
          Stripe reports back (subscription status, plan tier, invoice history), never your full card
          number.
        </P>
        <P>
          <strong className="text-[var(--tp-text)]">Infrastructure metrics</strong> — if you enroll a
          server with the TurboPanel daemon, that server reports host-level metrics (CPU, memory, disk,
          network, and — where enabled — ingress and database-proxy statistics) back to the control
          plane so we can show <em>you</em> your own dashboards. This is operational telemetry about
          infrastructure you control, not personal data about your end users, and it is never sold or
          shared outside of operating the service for you.
        </P>
        <P>
          <strong className="text-[var(--tp-text)]">Deployed application content</strong> — the code,
          containers, and data your deployed applications process are yours; we store and transmit them
          only as needed to run the service (for example, a Git checkout for a deploy, or a database
          your application connects to). We don&apos;t inspect or use this content for any purpose beyond
          delivering the service.
        </P>
        <P>
          <strong className="text-[var(--tp-text)]">Usage and log data</strong> — standard web request
          logs, session identifiers, and error diagnostics generated by using the control plane and web
          UI.
        </P>

        <H3>3. How we use it</H3>
        <P>
          To operate, secure, and improve the hosted service; to authenticate you and enforce
          organization boundaries; to process billing; to communicate service-relevant notices (security
          incidents, planned maintenance, changes to these policies); and to diagnose problems you or we
          report.
        </P>

        <H3>4. Cookies</H3>
        <P>
          The hosted service uses a session cookie to keep you signed in. There is no third-party
          advertising or cross-site tracking on <code>turbopanel.app</code>.
        </P>

        <H3>5. Who we share it with</H3>
        <P>
          We share data only with the subprocessors needed to run the service: Stripe (payments),
          Cloudflare (hosting, network, and edge infrastructure the control plane and UI run on), and — for
          organizations that connect one — GitHub or GitLab (repository access via the App/OAuth
          integration you authorize). We do not sell personal data, and we do not share it with anyone
          else except where required by law or with your direction.
        </P>

        <H3>6. Data retention</H3>
        <P>
          Account and billing records are kept for as long as your account is active and for a period
          after closure as needed for legal, tax, and dispute-resolution purposes. Infrastructure metrics
          are retained on a rolling window sized to the reporting views the product offers, not
          indefinitely. Deleting your account or disenrolling a server removes what we hold for it,
          subject to the retention above.
        </P>

        <H3>7. Your rights</H3>
        <P>
          Depending on where you live, you may have the right to access, correct, export, or delete the
          personal data we hold about you, and to object to or restrict certain processing. Request any
          of these at{' '}
          <a href="mailto:privacy@turbopanel.io" className="text-[var(--tp-accent)] hover:underline">
            privacy@turbopanel.io
          </a>{' '}
          [confirm inbox exists before publishing]. We&apos;ll respond within the timeframe your local
          law requires. [GDPR/CCPA-specific language — legal basis for processing, EU representative if
          applicable — to be set with counsel.]
        </P>

        <H3>8. Security</H3>
        <P>
          Secrets are sealed at rest under a rotatable root key; passwords and tokens are never stored in
          plain text. See the{' '}
          <a href="/security" className="text-[var(--tp-accent)] hover:underline">
            security page
          </a>{' '}
          for how to report a vulnerability. No system is perfectly secure, and we can&apos;t guarantee
          absolute security of information transmitted to the hosted service.
        </P>

        <H3>9. Children&apos;s privacy</H3>
        <P>
          The hosted service is not directed at children under 16, and we do not knowingly collect
          personal data from them.
        </P>

        <H3>10. International transfers</H3>
        <P>
          [Where data is processed and stored, and the mechanism relied on for cross-border transfer —
          to be set with counsel once hosting regions are finalized.]
        </P>

        <H3>11. Changes to this policy</H3>
        <P>
          We&apos;ll update the date above when this policy changes, and post material changes here
          before they take effect.
        </P>

        <H3>12. Contact</H3>
        <P>
          <a href="mailto:privacy@turbopanel.io" className="text-[var(--tp-accent)] hover:underline">
            privacy@turbopanel.io
          </a>{' '}
          — or [Company Legal Name], [Registered Address].
        </P>
      </MarketingSection>
    </MarketingPageShell>
  )
}
